# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted]
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x /home/ubuntu/stock-actions-runner/stock_work/stock/stock/gradlew

    - name: Properties File Copy
      run: cp /home/ubuntu/stock/application.properties /home/ubuntu/stock-actions-runner/stock_work/stock/stock/src/main/resources/application.properties

    - name: Build with Gradle
      run: /home/ubuntu/stock-actions-runner/stock_work/stock/stock/gradlew clean build -x check

    - name: backup
      run: mv /home/ubuntu/stock/stock-0.0.1-master.jar /home/ubuntu/stock/bak/stock-0.0.1-SNAPSHOT.jar_$(date '+%Y%m%d-%H%M%S')

    - name: deploy
      run: mv /home/ubuntu/stock-actions-runner/stock_work/stock/stock/build/libs/stock-0.0.1-SNAPSHOT.jar /home/ubuntu/stock/stock-0.0.1-master.jar

    - name: run
      run: cd /home/ubuntu/notify && ./notify.sh
